import type { CustomerPortfolio, Deal, Lead, Task } from "./types";

const portfolioShell = (
  partial: Pick<
    CustomerPortfolio,
    | "id"
    | "nr"
    | "companyName"
    | "registrationNumber"
    | "contractNo"
    | "period"
    | "scope"
    | "feeEur"
    | "emailForInvoices"
    | "clientContactName"
    | "clientContactPosition"
    | "sanctionsCheck"
    | "address"
    | "infoRequestDeadline"
    | "reportDraft"
    | "finalReport"
  > &
    Partial<Pick<CustomerPortfolio, "firstInvoiceAmountEur" | "secondInvoiceAmountEur" | "thirdInvoiceAmountEur">>,
): CustomerPortfolio => {
  const fee = partial.feeEur ?? 0;
  const q1 = Math.round(fee * 0.25);
  const q2 = Math.round(fee * 0.5);
  const q3 = fee - q1 - q2;
  return {
    lursoft: null,
    industry: null,
    naceCode: null,
    kycForm: null,
    idCopy: null,
    meetingDate: null,
    clientAcceptanceComplete: null,
    riskLevel: null,
    contractSigned: null,
    contractDate: null,
    additionalInvoicing: null,
    invoiceCheck: 0,
    contactEmail: null,
    whatsapp: null,
    lastContactDate: null,
    language: "English",
    framework: "Applicable statutory requirements",
    ...partial,
    firstInvoicePercent: "25%",
    firstInvoiceAmountEur: partial.firstInvoiceAmountEur ?? q1,
    secondInvoicePercent: "50%",
    secondInvoiceAmountEur: partial.secondInvoiceAmountEur ?? q2,
    thirdInvoicePercent: "25%",
    thirdInvoiceAmountEur: partial.thirdInvoiceAmountEur ?? q3,
    sanctionsCheck:
      partial.sanctionsCheck ?? partial.companyName ?? null,
  };
};

export const leads: Lead[] = [
  {
    id: "l1",
    company: "Baltic Freight Co.",
    contactName: "Marta Liepa",
    email: "marta@balticfreight.lt",
    stage: "qualified",
    valueEur: 42000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-12",
  },
  {
    id: "l2",
    company: "Nordic SaaS Labs",
    contactName: "Jonas Berg",
    email: "jonas@nordicsaas.io",
    stage: "contacted",
    valueEur: 18500,
    owner: "Laura Ozola",
    updatedAt: "2026-05-11",
  },
  {
    id: "l3",
    company: "Helios Retail",
    contactName: "Sofia Marin",
    email: "sofia@helios.ee",
    stage: "new",
    valueEur: 67000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-10",
  },
  {
    id: "l4",
    company: "Vilnius Metalworks UAB",
    contactName: "Tomas Vasiliauskas",
    email: "tomas@vmetal.lt",
    stage: "qualified",
    valueEur: 58000,
    owner: "Laura Ozola",
    updatedAt: "2026-05-13",
  },
  {
    id: "l5",
    company: "Fjord Analytics AS",
    contactName: "Ingrid Solheim",
    email: "ingrid@fjordanalytics.no",
    stage: "contacted",
    valueEur: 92000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-09",
  },
  {
    id: "l6",
    company: "Liepaja Industrial Park",
    contactName: "Gints Ozols",
    email: "g.ozols@rpl.lv",
    stage: "new",
    valueEur: 34000,
    owner: "Miks Abols",
    updatedAt: "2026-05-08",
  },
  {
    id: "l7",
    company: "Stockholm Fintech Hub",
    contactName: "Elin Forsberg",
    email: "elin@sfth.se",
    stage: "qualified",
    valueEur: 127500,
    owner: "Laura Ozola",
    updatedAt: "2026-05-14",
  },
  {
    id: "l8",
    company: "MedPark Diagnostics",
    contactName: "Dr. Lauma Kaleja",
    email: "lauma@medpark.lv",
    stage: "contacted",
    valueEur: 41500,
    owner: "Anna Straume",
    updatedAt: "2026-05-07",
  },
  {
    id: "l9",
    company: "CarbonLedger OÜ",
    contactName: "Martin Tamm",
    email: "martin@carbonledger.ee",
    stage: "new",
    valueEur: 78000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-06",
  },
  {
    id: "l10",
    company: "Kraków Robotics SP zoo",
    contactName: "Paweł Nowicki",
    email: "p.nowicki@kr-robo.pl",
    stage: "lost",
    valueEur: 21000,
    owner: "Miks Abols",
    updatedAt: "2026-04-28",
  },
  {
    id: "l11",
    company: "Dalku Logistics SIA",
    contactName: "Renate Liepina",
    email: "renate@dalkulog.lv",
    stage: "qualified",
    valueEur: 49600,
    owner: "Laura Ozola",
    updatedAt: "2026-05-13",
  },
  {
    id: "l12",
    company: "Helsinki Cleantech Oy",
    contactName: "Olli Virtanen",
    email: "olli@helsinkicleantech.fi",
    stage: "contacted",
    valueEur: 103000,
    owner: "Anna Straume",
    updatedAt: "2026-05-05",
  },
  {
    id: "l13",
    company: "DigiFarm Latvia",
    contactName: "Martins Celms",
    email: "martins@digifarm.lv",
    stage: "new",
    valueEur: 28900,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-04",
  },
  {
    id: "l14",
    company: "Odense Maritime Services",
    contactName: "Mette Hansen",
    email: "mette@odensemaritime.dk",
    stage: "qualified",
    valueEur: 71500,
    owner: "Laura Ozola",
    updatedAt: "2026-05-12",
  },
  {
    id: "l15",
    company: "SnowPeak Hosting AB",
    contactName: "Johan Ekström",
    email: "johan@snowpeakhosting.se",
    stage: "contacted",
    valueEur: 54800,
    owner: "Miks Abols",
    updatedAt: "2026-05-03",
  },
  {
    id: "l16",
    company: "Tartu Biotech LLC",
    contactName: "Kadi Paju",
    email: "kadi@tartubiotech.ee",
    stage: "new",
    valueEur: 61200,
    owner: "Anna Straume",
    updatedAt: "2026-05-02",
  },
  {
    id: "l17",
    company: "BlackSea Grain Terminal",
    contactName: "Ion Popescu",
    email: "ion@bsgrain.ro",
    stage: "lost",
    valueEur: 155000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-04-15",
  },
  {
    id: "l18",
    company: "Saldus FoodTech",
    contactName: "Liga Krumina",
    email: "liga@saldusfood.lv",
    stage: "qualified",
    valueEur: 37200,
    owner: "Laura Ozola",
    updatedAt: "2026-05-14",
  },
  {
    id: "l19",
    company: "Berlin AI Compliance GmbH",
    contactName: "Clara Weber",
    email: "clara@baic.de",
    stage: "contacted",
    valueEur: 88400,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-01",
  },
  {
    id: "l20",
    company: "Liepaja Port Terminal",
    contactName: "Uldis Grants",
    email: "uldis@los.lv",
    stage: "new",
    valueEur: 95600,
    owner: "Miks Abols",
    updatedAt: "2026-04-30",
  },
  {
    id: "l21",
    company: "Kaunas Smart Grid",
    contactName: "Darius Linge",
    email: "darius@ksgrid.lt",
    stage: "qualified",
    valueEur: 63900,
    owner: "Anna Straume",
    updatedAt: "2026-05-11",
  },
  {
    id: "l22",
    company: "Northwind Ventures",
    contactName: "Sara Lindqvist",
    email: "sara@northwind.vc",
    stage: "contacted",
    valueEur: 222000,
    owner: "Laura Ozola",
    updatedAt: "2026-05-13",
  },
];

/** Demo rows aligned with the CLIENT PORTFOLIO sheet column layout (spreadsheet template). */
export const customers: CustomerPortfolio[] = [
  portfolioShell({
    id: "c-all-in",
    nr: 1,
    companyName: "SIA ALL IN",
    registrationNumber: 40103860926,
    contractNo: "23/8",
    period: "2022",
    scope: "Statutory financial statements audit",
    feeEur: 2200,
    emailForInvoices: "coco@loco.lv",
    clientContactName: "Janis Banis",
    clientContactPosition: "CEO",
    sanctionsCheck: 'Limited liability company "ALL IN"',
    address: "18-8 Ernesta Birznieka-Upisha St., Riga LV-1050",
    infoRequestDeadline: "04.02.2023",
    reportDraft: "06.02.2023",
    finalReport: "10.02.2023",
    firstInvoiceAmountEur: 550,
    secondInvoiceAmountEur: 1100,
    thirdInvoiceAmountEur: 550,
  }),
  portfolioShell({
    id: "c-xxx",
    nr: 2,
    companyName: "XXX SIA",
    registrationNumber: 42103077952,
    contractNo: "23/9",
    period: "2022",
    scope: "Limited assurance review of financial statements (SPUS 2400)",
    feeEur: 1600,
    emailForInvoices: "Furightback@gmail.com",
    clientContactName: "Ilze Milze",
    clientContactPosition: "CFO",
    sanctionsCheck: "XXX SIA",
    address: "12-38 Atmodas Blvd., Liepaja LV-3414",
    infoRequestDeadline: "24.02.2023",
    reportDraft: "03.03.2023",
    finalReport: "31.03.2023",
    firstInvoiceAmountEur: 400,
    secondInvoiceAmountEur: 800,
    thirdInvoiceAmountEur: 400,
  }),
  portfolioShell({
    id: "c-greenlane",
    nr: 3,
    companyName: "GreenLane Logistics SIA",
    registrationNumber: 40203344771,
    contractNo: "24/14",
    period: "2025",
    scope: "Group consolidated reporting · audit readiness",
    feeEur: 8900,
    emailForInvoices: "finance@greenlane.lv",
    clientContactName: "Kristaps Plume",
    clientContactPosition: "Finance Director",
    sanctionsCheck: "GreenLane Logistics SIA",
    address: "72 Mukusalas St., Riga LV-1004",
    infoRequestDeadline: "18.06.2025",
    reportDraft: "01.07.2025",
    finalReport: "15.07.2025",
  }),
  portfolioShell({
    id: "c-wave",
    nr: 4,
    companyName: "Wave Payments Baltic SIA",
    registrationNumber: 40103999102,
    contractNo: "25/3",
    period: "2025–2026",
    scope: "IFRS reporting support and audit preparation",
    feeEur: 12400,
    emailForInvoices: "billing@wavepayments.eu",
    clientContactName: "Annika Vitola",
    clientContactPosition: "Head of Accounting",
    sanctionsCheck: "Wave Payments Baltic SIA",
    address: "50 Skanstes St., Riga LV-1013",
    infoRequestDeadline: "22.08.2025",
    reportDraft: "05.09.2025",
    finalReport: "20.09.2025",
  }),
  portfolioShell({
    id: "c-rigatech",
    nr: 5,
    companyName: "Riga Tech Campus AS (Latvia branch)",
    registrationNumber: "LV40203988771",
    contractNo: "24/21",
    period: "2024",
    scope: "Project oversight controls testing",
    feeEur: 5600,
    emailForInvoices: "ops@rigatechcampus.lv",
    clientContactName: "Pauls Eglitis",
    clientContactPosition: "COO",
    sanctionsCheck: "Riga Tech Campus AS (Latvia branch)",
    address: "Local address pending · Riga",
    infoRequestDeadline: "12.04.2025",
    reportDraft: "22.04.2025",
    finalReport: "30.04.2025",
  }),
  portfolioShell({
    id: "c-helios",
    nr: 6,
    companyName: "Helios Retail Eesti OÜ (Latvia project)",
    registrationNumber: 48503026128,
    contractNo: "25/7",
    period: "2025",
    scope: "International group compliance assessment",
    feeEur: 7200,
    emailForInvoices: "finance@heliosretail.ee",
    clientContactName: "Sofia Marin",
    clientContactPosition: "Regional CFO",
    sanctionsCheck: "Helios Retail Eesti OÜ",
    address: "Tallinn hub · Latvia customer record",
    infoRequestDeadline: "03.05.2025",
    reportDraft: "18.05.2025",
    finalReport: "28.05.2025",
  }),
  portfolioShell({
    id: "c-baltfreight",
    nr: 7,
    companyName: "Baltic Freight Terminal SIA",
    registrationNumber: 42103111409,
    contractNo: "23/41",
    period: "2023",
    scope: "Inventory and internal controls review",
    feeEur: 3150,
    emailForInvoices: "marta@balticfreight.lt",
    clientContactName: "Marta Liepa",
    clientContactPosition: "CEO",
    sanctionsCheck: "Baltic Freight Terminal SIA",
    address: "Riga Freeport, site 12, LV-1015",
    infoRequestDeadline: "14.03.2025",
    reportDraft: "22.03.2025",
    finalReport: "05.04.2025",
  }),
  portfolioShell({
    id: "c-nordicsaas",
    nr: 8,
    companyName: "Nordic SaaS Labs AB (LV)",
    registrationNumber: "SE5566778899-LV",
    contractNo: "24/33",
    period: "2024",
    scope: "AR recognition for liabilities and revenue · SaaS",
    feeEur: 9800,
    emailForInvoices: "jonas@nordicsaas.io",
    clientContactName: "Jonas Berg",
    clientContactPosition: "Founder",
    sanctionsCheck: "Nordic SaaS Labs AB",
    address: "Remote-first · Latvia tax advisory",
    infoRequestDeadline: "08.07.2025",
    reportDraft: "20.07.2025",
    finalReport: "02.08.2025",
  }),
  portfolioShell({
    id: "c-vmetal",
    nr: 9,
    companyName: "Vilnius Metalworks Latvia branch",
    registrationNumber: 40203901234,
    contractNo: "25/11",
    period: "2025",
    scope: "Health & safety and interim controls audit preparation",
    feeEur: 4400,
    emailForInvoices: "tomas@vmetal.lt",
    clientContactName: "Tomas Vasiliauskas",
    clientContactPosition: "Plant Manager",
    sanctionsCheck: "Vilnius Metalworks UAB",
    address: "Liepaja SEZ, LV-3414",
    infoRequestDeadline: "16.09.2025",
    reportDraft: "28.09.2025",
    finalReport: "12.10.2025",
  }),
  portfolioShell({
    id: "c-medpark",
    nr: 10,
    companyName: "MedPark Diagnostics SIA",
    registrationNumber: 40103288901,
    contractNo: "24/8",
    period: "2024",
    scope: "Public procurement project accounting",
    feeEur: 5100,
    emailForInvoices: "lauma@medpark.lv",
    clientContactName: "Dr. Lauma Kaleja",
    clientContactPosition: "CEO",
    sanctionsCheck: "MedPark Diagnostics SIA",
    address: "5a Braslas St., Riga LV-1035",
    infoRequestDeadline: "01.06.2025",
    reportDraft: "14.06.2025",
    finalReport: "25.06.2025",
  }),
  portfolioShell({
    id: "c-digifarm",
    nr: 11,
    companyName: "DigiFarm Latvia SIA",
    registrationNumber: 42103290122,
    contractNo: "25/19",
    period: "2025",
    scope: "Grant accounting and subsidy reporting preparation",
    feeEur: 2750,
    emailForInvoices: "martins@digifarm.lv",
    clientContactName: "Martins Celms",
    clientContactPosition: "Managing Partner",
    sanctionsCheck: "DigiFarm Latvia SIA",
    address: "62 Valdemara St., Riga LV-1013",
    infoRequestDeadline: "11.08.2025",
    reportDraft: "22.08.2025",
    finalReport: "05.09.2025",
  }),
  portfolioShell({
    id: "c-saldus",
    nr: 12,
    companyName: "Saldus FoodTech SIA",
    registrationNumber: 42103199877,
    contractNo: "25/4",
    period: "2025",
    scope: "Manufacturing cost accounting and margin analysis",
    feeEur: 3900,
    emailForInvoices: "liga@saldusfood.lv",
    clientContactName: "Liga Krumina",
    clientContactPosition: "CFO",
    sanctionsCheck: "Saldus FoodTech SIA",
    address: "10 Zemgales St., Saldus LV-3801",
    infoRequestDeadline: "05.05.2025",
    reportDraft: "18.05.2025",
    finalReport: "30.05.2025",
  }),
  portfolioShell({
    id: "c-fjord",
    nr: 13,
    companyName: "Fjord Analytics AS",
    registrationNumber: 923456785,
    contractNo: "25/31",
    period: "2025",
    scope: "SOC 2 readiness assessment and control mapping",
    feeEur: 18200,
    emailForInvoices: "finance@fjordanalytics.no",
    clientContactName: "Ingrid Solheim",
    clientContactPosition: "COO",
    sanctionsCheck: "Fjord Analytics AS",
    address: "Fornebu Brygge 3, 1360 Fornebu, Norway",
    infoRequestDeadline: "02.09.2025",
    reportDraft: "20.09.2025",
    finalReport: "04.10.2025",
  }),
  portfolioShell({
    id: "c-carbonledger",
    nr: 14,
    companyName: "CarbonLedger OÜ",
    registrationNumber: 14576987,
    contractNo: "25/42",
    period: "2025–2026",
    scope: "ESG disclosure assurance and carbon inventory review",
    feeEur: 12450,
    emailForInvoices: "martin@carbonledger.ee",
    clientContactName: "Martin Tamm",
    clientContactPosition: "Founder",
    sanctionsCheck: "CarbonLedger OÜ",
    address: "Narva mnt 7, 10117 Tallinn, Estonia",
    infoRequestDeadline: "15.09.2025",
    reportDraft: "28.09.2025",
    finalReport: "12.10.2025",
  }),
  portfolioShell({
    id: "c-helsinki-clean",
    nr: 15,
    companyName: "Helsinki Cleantech Oy",
    registrationNumber: 2894736-2,
    contractNo: "24/55",
    period: "2024–2025",
    scope: "R&D tax credit documentation and revenue recognition review",
    feeEur: 9600,
    emailForInvoices: "olli@helsinkicleantech.fi",
    clientContactName: "Olli Virtanen",
    clientContactPosition: "CFO",
    sanctionsCheck: "Helsinki Cleantech Oy",
    address: "Vuorikatu 14 A, 00100 Helsinki, Finland",
    infoRequestDeadline: "08.10.2025",
    reportDraft: "22.10.2025",
    finalReport: "05.11.2025",
  }),
  portfolioShell({
    id: "c-sfth",
    nr: 16,
    companyName: "Stockholm Fintech Hub AB",
    registrationNumber: 5568123456,
    contractNo: "25/18",
    period: "2025",
    scope: "Regulatory reporting controls and liquidity stress testing support",
    feeEur: 28500,
    emailForInvoices: "elin@sfth.se",
    clientContactName: "Elin Forsberg",
    clientContactPosition: "Head of Risk",
    sanctionsCheck: "Stockholm Fintech Hub AB",
    address: "Birger Jarlsgatan 57, 113 56 Stockholm, Sweden",
    infoRequestDeadline: "01.11.2025",
    reportDraft: "18.11.2025",
    finalReport: "02.12.2025",
  }),
  portfolioShell({
    id: "c-tartu-bio",
    nr: 17,
    companyName: "Tartu Biotech LLC",
    registrationNumber: 10886789,
    contractNo: "25/27",
    period: "2025",
    scope: "Grant compliance audit and milestone expenditure verification",
    feeEur: 6700,
    emailForInvoices: "kadi@tartubiotech.ee",
    clientContactName: "Kadi Paju",
    clientContactPosition: "Finance Lead",
    sanctionsCheck: "Tartu Biotech LLC",
    address: "Riia 181b, 50411 Tartu, Estonia",
    infoRequestDeadline: "12.11.2025",
    reportDraft: "25.11.2025",
    finalReport: "09.12.2025",
  }),
  portfolioShell({
    id: "c-odense",
    nr: 18,
    companyName: "Odense Maritime Services ApS",
    registrationNumber: 35271841,
    contractNo: "24/63",
    period: "2024–2025",
    scope: "Dry-dock capex capitalization and lease accounting review",
    feeEur: 14300,
    emailForInvoices: "mette@odensemaritime.dk",
    clientContactName: "Mette Hansen",
    clientContactPosition: "Controller",
    sanctionsCheck: "Odense Maritime Services ApS",
    address: "Havnegade 21, 5000 Odense, Denmark",
    infoRequestDeadline: "20.11.2025",
    reportDraft: "05.12.2025",
    finalReport: "18.12.2025",
  }),
  portfolioShell({
    id: "c-snowpeak",
    nr: 19,
    companyName: "SnowPeak Hosting AB",
    registrationNumber: 5590128844,
    contractNo: "25/36",
    period: "2025–2026",
    scope: "Recurring revenue recognition and deferred revenue reconciliation",
    feeEur: 11200,
    emailForInvoices: "johan@snowpeakhosting.se",
    clientContactName: "Johan Ekstrom",
    clientContactPosition: "VP Finance",
    sanctionsCheck: "SnowPeak Hosting AB",
    address: "Master Samuelsgatan 36, 111 57 Stockholm, Sweden",
    infoRequestDeadline: "28.11.2025",
    reportDraft: "12.12.2025",
    finalReport: "20.12.2025",
  }),
  portfolioShell({
    id: "c-berlin-ai",
    nr: 20,
    companyName: "Berlin AI Compliance GmbH",
    registrationNumber: "HRB 228891 B",
    contractNo: "25/44",
    period: "2025",
    scope: "EU AI Act governance gap analysis and documentation pack",
    feeEur: 19800,
    emailForInvoices: "clara@baic.de",
    clientContactName: "Clara Weber",
    clientContactPosition: "Legal & Compliance",
    sanctionsCheck: "Berlin AI Compliance GmbH",
    address: "Rosenthaler Strasse 43, 10178 Berlin, Germany",
    infoRequestDeadline: "05.12.2025",
    reportDraft: "18.12.2025",
    finalReport: "08.01.2026",
  }),
  portfolioShell({
    id: "c-kaunas-grid",
    nr: 21,
    companyName: "Kaunas Smart Grid UAB",
    registrationNumber: 305847392,
    contractNo: "24/71",
    period: "2024–2025",
    scope: "Utility revenue accounting and regulatory tariff true-up",
    feeEur: 8800,
    emailForInvoices: "darius@ksgrid.lt",
    clientContactName: "Darius Linge",
    clientContactPosition: "CFO",
    sanctionsCheck: "Kaunas Smart Grid UAB",
    address: "Laisves al. 94, 44200 Kaunas, Lithuania",
    infoRequestDeadline: "10.12.2025",
    reportDraft: "22.12.2025",
    finalReport: "06.01.2026",
  }),
  portfolioShell({
    id: "c-northwind",
    nr: 22,
    companyName: "Northwind Ventures AB",
    registrationNumber: 5590888211,
    contractNo: "25/52",
    period: "2025–2026",
    scope: "Fund LP reporting controls and carried interest model review",
    feeEur: 45200,
    emailForInvoices: "sara@northwind.vc",
    clientContactName: "Sara Lindqvist",
    clientContactPosition: "Managing Partner",
    sanctionsCheck: "Northwind Ventures AB",
    address: "Humlegardsgatan 10, 114 46 Stockholm, Sweden",
    infoRequestDeadline: "15.12.2025",
    reportDraft: "05.01.2026",
    finalReport: "22.01.2026",
  }),
];

export const deals: Deal[] = [
  {
    id: "d1",
    title: "Company-wide rollout, Wave Payments",
    company: "Wave Payments",
    stage: "negotiation",
    valueEur: 84000,
    probability: 65,
    closeDate: "2026-05-28",
    owner: "Edgars Kalnins",
  },
  {
    id: "d2",
    title: "Renewal + upsell, Riga Tech Campus",
    company: "Riga Tech Campus",
    stage: "proposal",
    valueEur: 132000,
    probability: 55,
    closeDate: "2026-06-05",
    owner: "Laura Ozola",
  },
  {
    id: "d3",
    title: "Pilot expansion, Helios Retail",
    company: "Helios Retail",
    stage: "qualification",
    valueEur: 54000,
    probability: 35,
    closeDate: "2026-06-18",
    owner: "Edgars Kalnins",
  },
  {
    id: "d4",
    title: "GreenLane, workflow automation",
    company: "GreenLane Logistics",
    stage: "won",
    valueEur: 31000,
    probability: 100,
    closeDate: "2026-04-22",
    owner: "Laura Ozola",
  },
  {
    id: "d5",
    title: "Enterprise SOC 2 readiness, Nordic SaaS Labs",
    company: "Nordic SaaS Labs",
    stage: "negotiation",
    valueEur: 97000,
    probability: 58,
    closeDate: "2026-06-02",
    owner: "Laura Ozola",
  },
  {
    id: "d6",
    title: "Terminal automation phase 2, Baltic Freight",
    company: "Baltic Freight Co.",
    stage: "proposal",
    valueEur: 61500,
    probability: 48,
    closeDate: "2026-06-12",
    owner: "Edgars Kalnins",
  },
  {
    id: "d7",
    title: "Fjord Analytics, embedded FP&A suite",
    company: "Fjord Analytics AS",
    stage: "qualification",
    valueEur: 118000,
    probability: 32,
    closeDate: "2026-07-08",
    owner: "Anna Straume",
  },
  {
    id: "d8",
    title: "CarbonLedger, carbon audit tooling",
    company: "CarbonLedger OÜ",
    stage: "proposal",
    valueEur: 76500,
    probability: 52,
    closeDate: "2026-06-25",
    owner: "Edgars Kalnins",
  },
  {
    id: "d9",
    title: "Stockholm Fintech Hub, shared services MS",
    company: "Stockholm Fintech Hub",
    stage: "negotiation",
    valueEur: 205000,
    probability: 61,
    closeDate: "2026-05-30",
    owner: "Laura Ozola",
  },
  {
    id: "d10",
    title: "MedPark, radiology capex lease structure",
    company: "MedPark Diagnostics",
    stage: "qualification",
    valueEur: 44200,
    probability: 28,
    closeDate: "2026-07-01",
    owner: "Anna Straume",
  },
  {
    id: "d11",
    title: "Vilnius Metalworks, consolidations playbook",
    company: "Vilnius Metalworks UAB",
    stage: "proposal",
    valueEur: 88900,
    probability: 44,
    closeDate: "2026-06-30",
    owner: "Miks Abols",
  },
  {
    id: "d12",
    title: "Kaunas Smart Grid, regulatory filing bundle",
    company: "Kaunas Smart Grid",
    stage: "qualification",
    valueEur: 52300,
    probability: 38,
    closeDate: "2026-07-14",
    owner: "Anna Straume",
  },
  {
    id: "d13",
    title: "Odense Maritime, maintenance SaaS renewal",
    company: "Odense Maritime Services",
    stage: "won",
    valueEur: 47800,
    probability: 100,
    closeDate: "2026-03-19",
    owner: "Laura Ozola",
  },
  {
    id: "d14",
    title: "SnowPeak Hosting, Nordic expansion kit",
    company: "SnowPeak Hosting AB",
    stage: "negotiation",
    valueEur: 69200,
    probability: 63,
    closeDate: "2026-06-08",
    owner: "Miks Abols",
  },
  {
    id: "d15",
    title: "Northwind Ventures, portfolio reporting mandate",
    company: "Northwind Ventures",
    stage: "proposal",
    valueEur: 312000,
    probability: 41,
    closeDate: "2026-08-01",
    owner: "Laura Ozola",
  },
  {
    id: "d16",
    title: "Berlin AI Compliance, EU AI Act gap analysis",
    company: "Berlin AI Compliance GmbH",
    stage: "qualification",
    valueEur: 93600,
    probability: 29,
    closeDate: "2026-07-22",
    owner: "Edgars Kalnins",
  },
  {
    id: "d17",
    title: "Liepaja Port Terminal, berth optimisation",
    company: "Liepaja Port Terminal",
    stage: "proposal",
    valueEur: 151000,
    probability: 47,
    closeDate: "2026-06-28",
    owner: "Miks Abols",
  },
  {
    id: "d18",
    title: "Legacy ERP sunset, Kraków Robotics",
    company: "Kraków Robotics SP zoo",
    stage: "lost",
    valueEur: 24000,
    probability: 0,
    closeDate: "2026-04-02",
    owner: "Miks Abols",
  },
  {
    id: "d19",
    title: "Tartu Biotech, grant reporting automation",
    company: "Tartu Biotech LLC",
    stage: "won",
    valueEur: 38900,
    probability: 100,
    closeDate: "2026-02-14",
    owner: "Anna Straume",
  },
  {
    id: "d20",
    title: "Helsinki Cleantech, carbon credits desk",
    company: "Helsinki Cleantech Oy",
    stage: "negotiation",
    valueEur: 174500,
    probability: 54,
    closeDate: "2026-07-05",
    owner: "Laura Ozola",
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Send revised proposal to Wave Payments",
    relatedTo: "Deal · Wave Payments",
    dueAt: "2026-05-13T16:00:00",
    priority: "high",
    done: false,
    assignee: "Edgars Kalnins",
  },
  {
    id: "t2",
    title: "Quarterly review deck, Riga Tech Campus",
    relatedTo: "Customer · Riga Tech Campus",
    dueAt: "2026-05-14T11:30:00",
    priority: "medium",
    done: false,
    assignee: "Laura Ozola",
  },
  {
    id: "t3",
    title: "Follow-up call, Nordic SaaS Labs",
    relatedTo: "Lead · Nordic SaaS Labs",
    dueAt: "2026-05-13T09:00:00",
    priority: "high",
    done: true,
    assignee: "Laura Ozola",
  },
  {
    id: "t4",
    title: "Prep SOC 2 evidence folder, Nordic SaaS Labs",
    relatedTo: "Deal · Nordic SaaS Labs",
    dueAt: "2026-05-15T14:00:00",
    priority: "high",
    done: false,
    assignee: "Laura Ozola",
  },
  {
    id: "t5",
    title: "Schedule exec workshop, Stockholm Fintech Hub",
    relatedTo: "Deal · Stockholm Fintech Hub",
    dueAt: "2026-05-16T10:00:00",
    priority: "medium",
    done: false,
    assignee: "Edgars Kalnins",
  },
  {
    id: "t6",
    title: "Draft LOI terms, Northwind Ventures",
    relatedTo: "Deal · Northwind Ventures",
    dueAt: "2026-05-18T17:00:00",
    priority: "high",
    done: false,
    assignee: "Laura Ozola",
  },
  {
    id: "t7",
    title: "Invoice reconciliation, GreenLane logistics fees",
    relatedTo: "Customer · GreenLane Logistics",
    dueAt: "2026-05-13T12:00:00",
    priority: "medium",
    done: true,
    assignee: "Anna Straume",
  },
  {
    id: "t8",
    title: "CRM hygiene: merge duplicate Helios contacts",
    relatedTo: "Lead · Helios Retail",
    dueAt: "2026-05-17T09:30:00",
    priority: "low",
    done: false,
    assignee: "Miks Abols",
  },
  {
    id: "t9",
    title: "Legal review packet, Liepaja Port Terminal",
    relatedTo: "Deal · Liepaja Port Terminal",
    dueAt: "2026-05-19T15:00:00",
    priority: "high",
    done: false,
    assignee: "Edgars Kalnins",
  },
  {
    id: "t10",
    title: "Send pricing bands, Berlin AI Compliance",
    relatedTo: "Deal · Berlin AI Compliance GmbH",
    dueAt: "2026-05-20T11:00:00",
    priority: "medium",
    done: false,
    assignee: "Anna Straume",
  },
  {
    id: "t11",
    title: "Weekly pipeline scrub with Miks",
    relatedTo: "General · Sales cadence",
    dueAt: "2026-05-14T08:00:00",
    priority: "medium",
    done: true,
    assignee: "Laura Ozola",
  },
  {
    id: "t12",
    title: "Renew SnowPeak Hosting security questionnaire",
    relatedTo: "Deal · SnowPeak Hosting AB",
    dueAt: "2026-05-21T13:45:00",
    priority: "low",
    done: false,
    assignee: "Miks Abols",
  },
  {
    id: "t13",
    title: "Prepare Tartu Biotech success story one-pager",
    relatedTo: "Customer · Tartu Biotech",
    dueAt: "2026-05-22T16:30:00",
    priority: "low",
    done: false,
    assignee: "Anna Straume",
  },
  {
    id: "t14",
    title: "Chase signature, Kaunas Smart Grid MSA",
    relatedTo: "Deal · Kaunas Smart Grid",
    dueAt: "2026-05-13T18:00:00",
    priority: "high",
    done: false,
    assignee: "Edgars Kalnins",
  },
  {
    id: "t15",
    title: "Upload Odense Maritime renewal files to DMS",
    relatedTo: "Deal · Odense Maritime Services",
    dueAt: "2026-05-12T10:00:00",
    priority: "medium",
    done: true,
    assignee: "Laura Ozola",
  },
  {
    id: "t16",
    title: "Prep Helsinki Cleantech board slides",
    relatedTo: "Deal · Helsinki Cleantech Oy",
    dueAt: "2026-05-23T09:00:00",
    priority: "high",
    done: false,
    assignee: "Laura Ozola",
  },
  {
    id: "t17",
    title: "Verify VAT IDs, Vilnius Metalworks cluster",
    relatedTo: "Deal · Vilnius Metalworks UAB",
    dueAt: "2026-05-24T14:15:00",
    priority: "medium",
    done: false,
    assignee: "Miks Abols",
  },
  {
    id: "t18",
    title: "Lead nurture sequence, BlackSea Grain (closed lost debrief)",
    relatedTo: "Lead · BlackSea Grain Terminal",
    dueAt: "2026-05-25T11:20:00",
    priority: "low",
    done: false,
    assignee: "Edgars Kalnins",
  },
  {
    id: "t19",
    title: "MedPark site visit coordination",
    relatedTo: "Deal · MedPark Diagnostics",
    dueAt: "2026-05-26T08:45:00",
    priority: "medium",
    done: false,
    assignee: "Anna Straume",
  },
  {
    id: "t20",
    title: "Update CarbonLedger mutual NDA redlines",
    relatedTo: "Deal · CarbonLedger OÜ",
    dueAt: "2026-05-27T17:30:00",
    priority: "high",
    done: false,
    assignee: "Edgars Kalnins",
  },
  {
    id: "t21",
    title: "Fjord Analytics discovery notes → CRM",
    relatedTo: "Deal · Fjord Analytics AS",
    dueAt: "2026-05-28T12:00:00",
    priority: "medium",
    done: false,
    assignee: "Laura Ozola",
  },
  {
    id: "t22",
    title: "DigiFarm subsidy checklist, client send-out",
    relatedTo: "Customer · DigiFarm Latvia",
    dueAt: "2026-05-29T10:30:00",
    priority: "low",
    done: true,
    assignee: "Anna Straume",
  },
  {
    id: "t23",
    title: "Quarterly tax calendar reminders, portfolio blast",
    relatedTo: "General · Customer success",
    dueAt: "2026-06-01T09:00:00",
    priority: "medium",
    done: false,
    assignee: "Laura Ozola",
  },
  {
    id: "t24",
    title: "Review lost deal, Kraków Robotics lessons learned",
    relatedTo: "Deal · Kraków Robotics SP zoo",
    dueAt: "2026-06-02T15:00:00",
    priority: "low",
    done: false,
    assignee: "Miks Abols",
  },
];
