import type { CustomerPortfolio, Deal, Lead, Task } from "./types";

export const leads: Lead[] = [
  {
    id: "l1",
    company: "Baltic Freight Co.",
    contactName: "Marta Liepa",
    email: "marta@balticfreight.lt",
    stage: "qualified",
    valueEur: 42000,
    owner: "Edgars Kalniņš",
    updatedAt: "2026-05-12",
  },
  {
    id: "l2",
    company: "Nordic SaaS Labs",
    contactName: "Jonas Berg",
    email: "jonas@nordicsaas.io",
    stage: "contacted",
    valueEur: 18500,
    owner: "Laura Ozola",
    updatedAt: "2026-05-11",
  },
  {
    id: "l3",
    company: "Helios Retail",
    contactName: "Sofia Marin",
    email: "sofia@helios.ee",
    stage: "new",
    valueEur: 67000,
    owner: "Edgars Kalniņš",
    updatedAt: "2026-05-10",
  },
];

/** Rows from Downloads/Klientu uzskaites reģistrs_template.xlsx → sheet «KLIENTU PORTFELIS». */
export const customers: CustomerPortfolio[] = [
  {
    id: "c-all-in",
    nr: 1,
    companyName: "SIA ALL IN",
    registrationNumber: 40103860926,
    lursoft: null,
    industry: null,
    naceCode: null,
    kycForm: null,
    idCopy: null,
    meetingDate: null,
    clientAcceptanceComplete: null,
    riskLevel: null,
    contractNo: "23/8",
    period: "2022",
    contractSigned: null,
    contractDate: null,
    scope: "Finanšu pārskatu revīzija",
    feeEur: 2200,
    firstInvoicePercent: "25%",
    firstInvoiceAmountEur: 550,
    secondInvoicePercent: "50%",
    secondInvoiceAmountEur: 1100,
    thirdInvoicePercent: "25%",
    thirdInvoiceAmountEur: 550,
    additionalInvoicing: null,
    invoiceCheck: 0,
    emailForInvoices: "coco@loco.lv",
    clientContactName: "Jānis Bānis",
    clientContactPosition: "CEO",
    contactEmail: null,
    whatsapp: null,
    lastContactDate: null,
    infoRequestDeadline: "04.02.2023",
    reportDraft: "06.02.2023",
    finalReport: "10.02.2023",
    language: "latviešu valodā",
    framework: "Latvijas normatīvo aktu prasībām",
    sanctionsCheck: 'Sabiedrība ar ierobežotu atbildību "ALL IN"',
    address: "Ernesta Birznieka-Upīša iela 18 - 8, Rīga, LV-1050",
  },
  {
    id: "c-xxx",
    nr: 2,
    companyName: "XXX SIA",
    registrationNumber: 42103077952,
    lursoft: null,
    industry: null,
    naceCode: null,
    kycForm: null,
    idCopy: null,
    meetingDate: null,
    clientAcceptanceComplete: null,
    riskLevel: null,
    contractNo: "23/9",
    period: "2022",
    contractSigned: null,
    contractDate: null,
    scope: "Finanšu pārskatu ierobežota pārbaude (SPUS 2400)",
    feeEur: 1600,
    firstInvoicePercent: "25%",
    firstInvoiceAmountEur: 400,
    secondInvoicePercent: "50%",
    secondInvoiceAmountEur: 800,
    thirdInvoicePercent: "25%",
    thirdInvoiceAmountEur: 400,
    additionalInvoicing: null,
    invoiceCheck: 0,
    emailForInvoices: "Furightback@gmail.com",
    clientContactName: "Ilze Milze",
    clientContactPosition: "CFO",
    contactEmail: null,
    whatsapp: null,
    lastContactDate: null,
    infoRequestDeadline: "24.02.2023",
    reportDraft: "03.03.2023",
    finalReport: "31.03.2023",
    language: "latviešu valodā",
    framework: "Latvijas normatīvo aktu prasībām",
    sanctionsCheck: "XXX SIA",
    address: "Atmodas bulvāris 12 - 38, Liepāja, LV-3414",
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    title: "Company-wide rollout — Wave Payments",
    company: "Wave Payments",
    stage: "negotiation",
    valueEur: 84000,
    probability: 65,
    closeDate: "2026-05-28",
    owner: "Edgars Kalniņš",
  },
  {
    id: "d2",
    title: "Renewal + upsell — Riga Tech Campus",
    company: "Riga Tech Campus",
    stage: "proposal",
    valueEur: 132000,
    probability: 55,
    closeDate: "2026-06-05",
    owner: "Laura Ozola",
  },
  {
    id: "d3",
    title: "Pilot expansion — Helios Retail",
    company: "Helios Retail",
    stage: "qualification",
    valueEur: 54000,
    probability: 35,
    closeDate: "2026-06-18",
    owner: "Edgars Kalniņš",
  },
  {
    id: "d4",
    title: "GreenLane — workflow automation",
    company: "GreenLane Logistics",
    stage: "won",
    valueEur: 31000,
    probability: 100,
    closeDate: "2026-04-22",
    owner: "Laura Ozola",
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Send revised proposal to Wave Payments",
    relatedTo: "Deal · Wave Payments",
    dueAt: "2026-05-13T16:00:00",
    priority: "high",
    done: false,
    assignee: "Edgars Kalniņš",
  },
  {
    id: "t2",
    title: "Quarterly review deck — Riga Tech Campus",
    relatedTo: "Customer · Riga Tech Campus",
    dueAt: "2026-05-14T11:30:00",
    priority: "medium",
    done: false,
    assignee: "Laura Ozola",
  },
  {
    id: "t3",
    title: "Follow-up call — Nordic SaaS Labs",
    relatedTo: "Lead · Nordic SaaS Labs",
    dueAt: "2026-05-13T09:00:00",
    priority: "high",
    done: true,
    assignee: "Laura Ozola",
  },
];
